--
- Bryant Park:
    :lat: 40.7532
    :lon: -73.9841
- Golden Gate:
    :lat: 37.7826
    :lon: -122.4107
- LA - Hollywood:
    :lat: 34.1015
    :lon: -118.3444
- Madison:
    :lat: 40.7506
    :lon: -73.9809
- Meatpacking:
    :lat: 40.7395
    :lon: -74.0061
- Midtown:
    :lat: 40.7483
    :lon: -73.9847
- SoMa:
    :lat: 37.7873
    :lon: -122.399
- Soho:
    :lat: 40.7199
    :lon: -73.9988
- Soho West:
    :lat: 40.727
    :lon: -74.0055
